CREATE TABLE STATS
(
    STAT_ID   INT(11)     NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STAT_DATE DATETIME    NOT NULL,
    STAT      VARCHAR(20) NOT NULL,
    VALUE     INT(11)     NOT NULL
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS BESTSELLERS
FROM BOOKS
WHERE BESTSELLER = 1;

DELIMITER $$
CREATE EVENT UPDATE_BESTSELLERS
    ON SCHEDULE EVERY 1 MINUTE DO
    BEGIN
        DECLARE bestsellers_num INT;

        CALL UpdateBestsellers();

        SELECT BESTSELLERS INTO bestsellers_num FROM BESTSELLERS_COUNT;

        INSERT INTO STATS(STAT_DATE, STAT, VALUE)
        VALUES (CURTIME(), 'BESTSELLERS', bestsellers_num);
    END $$
DELIMITER ;
