EXPLAIN SELECT * FROM READERS
WHERE FIRSTNAME = 'John';

CREATE INDEX IDX_TITLE ON BOOKS (TITLE);
CREATE INDEX IDX_NAME ON READERS (FIRSTNAME, LASTNAME);

EXPLAIN SELECT * FROM READERS
WHERE FIRSTNAME = 'John';